from common.utils.helper import getEnvVariables

WELLNESS_CAMPAIGN_CODE = getEnvVariables("WELLNESS_CAMPAIGN_CODE")
GPS_CAMPAIGN_CODE = getEnvVariables("GPS_CAMPAIGN_CODE")
WELLNESS_CAMPAIGN_TEMPLATE = getEnvVariables("WELLNESS_CAMPAIGN_TEMPLATE")
GPS_CAMPAIGN_TEMPLATE = getEnvVariables("GPS_CAMPAIGN_TEMPLATE")
CAMPAIGN_AUTH_ID = getEnvVariables("CAMPAIGN_AUTH_ID")
WELLNESS_CAMPAIGN_BUSINESS = getEnvVariables("WELLNESS_CAMPAIGN_BUSINESS")
GPS_CAMPAIGN_BUSINESS = getEnvVariables("GPS_CAMPAIGN_BUSINESS")
CAMPAIGN_ENCRYPTION_SECRET_KEY = getEnvVariables("CAMPAIGN_ENCRYPTION_SECRET_KEY")
WHATSAPP_ENDPOINT = getEnvVariables("WHATSAPP_ENDPOINT")
WELLNESS_CAMPAIGN_DETAILS = "MICIP Wellness Report"
GPS_CAMPAIGN_DETAILS = "MICIP Gps Report"
